/* tslint:disable */
/* eslint-disable */
/*
Officient API

Officient offers an intuitive HRIS which helps manage all personnel administration through our HR platform & personalized employee self-services. Manage payroll, company assets, contracts, days off, fleet, performance reviews and all employee data in one HR system. HR deserves great software and we're here to provide it.

We support our customers in transforming HR towards paperless administration and automating tedious workforce management tasks in the process. Our goal? Transform HR from an administrative, processing role, to a controlling role which fuels HR strategy across the organization.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { CostCenterDetailGet400Response } from '../models';
// @ts-ignore
import { CostCenterDetailGetResponse } from '../models';
// @ts-ignore
import { CostCenterGetListResponseInner } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * CostCenterApi - axios parameter creator
 * @export
 */
export const CostCenterApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get the details of all functions or that of a single one
         * @summary Cost center detail
         * @param {string} internalCode The internal code / GUID of the function you would like to receive information on
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        detailGet: async (internalCode: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'internalCode' is not null or undefined
            assertParamExists('detailGet', 'internalCode', internalCode)
            const localVarPath = `/1.0/wages/cost_centers/detail/{internal_code}`
                .replace(`{${"internal_code"}}`, encodeURIComponent(String(internalCode !== undefined ? internalCode : `-internal_code-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/1.0/wages/cost_centers/detail/{internal_code}',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get the details of all functions or that of a single one
         * @summary List cost centers
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getList: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/1.0/wages/cost_centers/list`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/1.0/wages/cost_centers/list',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CostCenterApi - functional programming interface
 * @export
 */
export const CostCenterApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CostCenterApiAxiosParamCreator(configuration)
    return {
        /**
         * Get the details of all functions or that of a single one
         * @summary Cost center detail
         * @param {CostCenterApiDetailGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async detailGet(requestParameters: CostCenterApiDetailGetRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CostCenterDetailGetResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.detailGet(requestParameters.internalCode, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Get the details of all functions or that of a single one
         * @summary List cost centers
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getList(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<CostCenterGetListResponseInner>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getList(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * CostCenterApi - factory interface
 * @export
 */
export const CostCenterApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CostCenterApiFp(configuration)
    return {
        /**
         * Get the details of all functions or that of a single one
         * @summary Cost center detail
         * @param {CostCenterApiDetailGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        detailGet(requestParameters: CostCenterApiDetailGetRequest, options?: AxiosRequestConfig): AxiosPromise<CostCenterDetailGetResponse> {
            return localVarFp.detailGet(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Get the details of all functions or that of a single one
         * @summary List cost centers
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getList(options?: AxiosRequestConfig): AxiosPromise<Array<CostCenterGetListResponseInner>> {
            return localVarFp.getList(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for detailGet operation in CostCenterApi.
 * @export
 * @interface CostCenterApiDetailGetRequest
 */
export type CostCenterApiDetailGetRequest = {
    
    /**
    * The internal code / GUID of the function you would like to receive information on
    * @type {string}
    * @memberof CostCenterApiDetailGet
    */
    readonly internalCode: string
    
}

/**
 * CostCenterApiGenerated - object-oriented interface
 * @export
 * @class CostCenterApiGenerated
 * @extends {BaseAPI}
 */
export class CostCenterApiGenerated extends BaseAPI {
    /**
     * Get the details of all functions or that of a single one
     * @summary Cost center detail
     * @param {CostCenterApiDetailGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CostCenterApiGenerated
     */
    public detailGet(requestParameters: CostCenterApiDetailGetRequest, options?: AxiosRequestConfig) {
        return CostCenterApiFp(this.configuration).detailGet(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get the details of all functions or that of a single one
     * @summary List cost centers
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CostCenterApiGenerated
     */
    public getList(options?: AxiosRequestConfig) {
        return CostCenterApiFp(this.configuration).getList(options).then((request) => request(this.axios, this.basePath));
    }
}
