/* tslint:disable */
/* eslint-disable */
/*
Officient API

Officient offers an intuitive HRIS which helps manage all personnel administration through our HR platform & personalized employee self-services. Manage payroll, company assets, contracts, days off, fleet, performance reviews and all employee data in one HR system. HR deserves great software and we're here to provide it.

We support our customers in transforming HR towards paperless administration and automating tedious workforce management tasks in the process. Our goal? Transform HR from an administrative, processing role, to a controlling role which fuels HR strategy across the organization.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { CostUnitGetFunctionsDetail400Response } from '../models';
// @ts-ignore
import { CostUnitGetFunctionsDetailResponse } from '../models';
// @ts-ignore
import { CostUnitListFunctionsResponseInner } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * CostUnitApi - axios parameter creator
 * @export
 */
export const CostUnitApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get the details of all functions or that of a single one
         * @summary Cost unit detail
         * @param {string} internalCode The internal code / GUID of the function you would like to receive information on
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFunctionsDetail: async (internalCode: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'internalCode' is not null or undefined
            assertParamExists('getFunctionsDetail', 'internalCode', internalCode)
            const localVarPath = `/1.0/wages/cost_units/detail/{internal_code}`
                .replace(`{${"internal_code"}}`, encodeURIComponent(String(internalCode !== undefined ? internalCode : `-internal_code-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/1.0/wages/cost_units/detail/{internal_code}',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get the details of all functions or that of a single one
         * @summary List cost units
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listFunctions: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/1.0/wages/cost_units/list`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/1.0/wages/cost_units/list',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CostUnitApi - functional programming interface
 * @export
 */
export const CostUnitApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CostUnitApiAxiosParamCreator(configuration)
    return {
        /**
         * Get the details of all functions or that of a single one
         * @summary Cost unit detail
         * @param {CostUnitApiGetFunctionsDetailRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getFunctionsDetail(requestParameters: CostUnitApiGetFunctionsDetailRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CostUnitGetFunctionsDetailResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getFunctionsDetail(requestParameters.internalCode, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Get the details of all functions or that of a single one
         * @summary List cost units
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listFunctions(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<CostUnitListFunctionsResponseInner>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listFunctions(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * CostUnitApi - factory interface
 * @export
 */
export const CostUnitApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CostUnitApiFp(configuration)
    return {
        /**
         * Get the details of all functions or that of a single one
         * @summary Cost unit detail
         * @param {CostUnitApiGetFunctionsDetailRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFunctionsDetail(requestParameters: CostUnitApiGetFunctionsDetailRequest, options?: AxiosRequestConfig): AxiosPromise<CostUnitGetFunctionsDetailResponse> {
            return localVarFp.getFunctionsDetail(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Get the details of all functions or that of a single one
         * @summary List cost units
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listFunctions(options?: AxiosRequestConfig): AxiosPromise<Array<CostUnitListFunctionsResponseInner>> {
            return localVarFp.listFunctions(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getFunctionsDetail operation in CostUnitApi.
 * @export
 * @interface CostUnitApiGetFunctionsDetailRequest
 */
export type CostUnitApiGetFunctionsDetailRequest = {
    
    /**
    * The internal code / GUID of the function you would like to receive information on
    * @type {string}
    * @memberof CostUnitApiGetFunctionsDetail
    */
    readonly internalCode: string
    
}

/**
 * CostUnitApiGenerated - object-oriented interface
 * @export
 * @class CostUnitApiGenerated
 * @extends {BaseAPI}
 */
export class CostUnitApiGenerated extends BaseAPI {
    /**
     * Get the details of all functions or that of a single one
     * @summary Cost unit detail
     * @param {CostUnitApiGetFunctionsDetailRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CostUnitApiGenerated
     */
    public getFunctionsDetail(requestParameters: CostUnitApiGetFunctionsDetailRequest, options?: AxiosRequestConfig) {
        return CostUnitApiFp(this.configuration).getFunctionsDetail(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get the details of all functions or that of a single one
     * @summary List cost units
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CostUnitApiGenerated
     */
    public listFunctions(options?: AxiosRequestConfig) {
        return CostUnitApiFp(this.configuration).listFunctions(options).then((request) => request(this.axios, this.basePath));
    }
}
