/*
Officient API

Officient offers an intuitive HRIS which helps manage all personnel administration through our HR platform & personalized employee self-services. Manage payroll, company assets, contracts, days off, fleet, performance reviews and all employee data in one HR system. HR deserves great software and we're here to provide it.

We support our customers in transforming HR towards paperless administration and automating tedious workforce management tasks in the process. Our goal? Transform HR from an administrative, processing role, to a controlling role which fuels HR strategy across the organization.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface AuthenticationGetAccessTokenRequest
 */
export interface AuthenticationGetAccessTokenRequest {
    /**
     * Authorization code in case of 3 legged oauth flow
     * @type {string}
     * @memberof AuthenticationGetAccessTokenRequest
     */
    'code'?: string;
    /**
     * client_id of your app. Can be found under \'my apps\'
     * @type {string}
     * @memberof AuthenticationGetAccessTokenRequest
     */
    'client_id'?: string;
    /**
     * client secret of your app. Can be found under \'my apps\'
     * @type {string}
     * @memberof AuthenticationGetAccessTokenRequest
     */
    'client_secret'?: string;
    /**
     * should always be either authorization_code or refresh_token
     * @type {string}
     * @memberof AuthenticationGetAccessTokenRequest
     */
    'grant_type'?: string;
    /**
     * optional
     * @type {string}
     * @memberof AuthenticationGetAccessTokenRequest
     */
    'refresh_token'?: string;
}

