/*
Officient API

Officient offers an intuitive HRIS which helps manage all personnel administration through our HR platform & personalized employee self-services. Manage payroll, company assets, contracts, days off, fleet, performance reviews and all employee data in one HR system. HR deserves great software and we're here to provide it.

We support our customers in transforming HR towards paperless administration and automating tedious workforce management tasks in the process. Our goal? Transform HR from an administrative, processing role, to a controlling role which fuels HR strategy across the organization.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BudgetAddBudgetItemRequest
 */
export interface BudgetAddBudgetItemRequest {
    /**
     * The type of budget.
     * @type {string}
     * @memberof BudgetAddBudgetItemRequest
     */
    'budget_type'?: string;
    /**
     * The maximum amount that will be set for the budget.
     * @type {number}
     * @memberof BudgetAddBudgetItemRequest
     */
    'maximum'?: number;
    /**
     * The year for which the budget will created.
     * @type {number}
     * @memberof BudgetAddBudgetItemRequest
     */
    'year'?: number;
    /**
     * The id of the employee for which the budget will be created.
     * @type {number}
     * @memberof BudgetAddBudgetItemRequest
     */
    'employee_id'?: number;
}

