/*
Officient API

Officient offers an intuitive HRIS which helps manage all personnel administration through our HR platform & personalized employee self-services. Manage payroll, company assets, contracts, days off, fleet, performance reviews and all employee data in one HR system. HR deserves great software and we're here to provide it.

We support our customers in transforming HR towards paperless administration and automating tedious workforce management tasks in the process. Our goal? Transform HR from an administrative, processing role, to a controlling role which fuels HR strategy across the organization.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ExpenseSetPayoutMethodAndStatusRequest
 */
export interface ExpenseSetPayoutMethodAndStatusRequest {
    /**
     * 
     * @type {string}
     * @memberof ExpenseSetPayoutMethodAndStatusRequest
     */
    'new_payout_method': ExpenseSetPayoutMethodAndStatusRequestNewPayoutMethodEnum;
    /**
     * 
     * @type {string}
     * @memberof ExpenseSetPayoutMethodAndStatusRequest
     */
    'payout_other_reason'?: string;
    /**
     * This field is required when the \"new\"payout_method\" is either PAYOUT_ACCOUNTING, PAYOUT_OTHER or PAYOUT_MANUALLY
     * @type {string}
     * @memberof ExpenseSetPayoutMethodAndStatusRequest
     */
    'payout_status'?: ExpenseSetPayoutMethodAndStatusRequestPayoutStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ExpenseSetPayoutMethodAndStatusRequest
     */
    'period'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExpenseSetPayoutMethodAndStatusRequest
     */
    'year'?: string;
}

type ExpenseSetPayoutMethodAndStatusRequestNewPayoutMethodEnum = 'UNDECIDED' | 'DO_NOT_PAYOUT' | 'PAYOUT_ACCOUNTING' | 'PAYOUT_OTHER' | 'PAYOUT_MANUALLY' | 'PAYOUT_USING_PAYROLL_PROVIDER'
type ExpenseSetPayoutMethodAndStatusRequestPayoutStatusEnum = 'PAID_OUT' | 'NOT_PAID_OUT'


