/*
Officient API

Officient offers an intuitive HRIS which helps manage all personnel administration through our HR platform & personalized employee self-services. Manage payroll, company assets, contracts, days off, fleet, performance reviews and all employee data in one HR system. HR deserves great software and we're here to provide it.

We support our customers in transforming HR towards paperless administration and automating tedious workforce management tasks in the process. Our goal? Transform HR from an administrative, processing role, to a controlling role which fuels HR strategy across the organization.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ExpenseListByYearResponseDataInner
 */
export interface ExpenseListByYearResponseDataInner {
    /**
     * 
     * @type {string}
     * @memberof ExpenseListByYearResponseDataInner
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExpenseListByYearResponseDataInner
     */
    'description'?: string;
    /**
     * 
     * @type {number}
     * @memberof ExpenseListByYearResponseDataInner
     */
    'id'?: number;
    /**
     * 
     * @type {number}
     * @memberof ExpenseListByYearResponseDataInner
     */
    'employee_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof ExpenseListByYearResponseDataInner
     */
    'date'?: string;
    /**
     * 
     * @type {number}
     * @memberof ExpenseListByYearResponseDataInner
     */
    'time_created'?: number;
    /**
     * 
     * @type {string}
     * @memberof ExpenseListByYearResponseDataInner
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExpenseListByYearResponseDataInner
     */
    'price'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExpenseListByYearResponseDataInner
     */
    'payout_method'?: string;
    /**
     * 
     * @type {any}
     * @memberof ExpenseListByYearResponseDataInner
     */
    'payout_period'?: any;
    /**
     * 
     * @type {any}
     * @memberof ExpenseListByYearResponseDataInner
     */
    'payout_period_frequency'?: any;
    /**
     * 
     * @type {any}
     * @memberof ExpenseListByYearResponseDataInner
     */
    'payout_year'?: any;
    /**
     * 
     * @type {number}
     * @memberof ExpenseListByYearResponseDataInner
     */
    'expense_category_id'?: number;
    /**
     * 
     * @type {any}
     * @memberof ExpenseListByYearResponseDataInner
     */
    'price_per_kilometer'?: any;
    /**
     * 
     * @type {any}
     * @memberof ExpenseListByYearResponseDataInner
     */
    'distance'?: any;
    /**
     * 
     * @type {any}
     * @memberof ExpenseListByYearResponseDataInner
     */
    'metadata'?: any;
    /**
     * 
     * @type {any}
     * @memberof ExpenseListByYearResponseDataInner
     */
    'dates'?: any;
    /**
     * 
     * @type {any}
     * @memberof ExpenseListByYearResponseDataInner
     */
    'date_approved'?: any;
    /**
     * 
     * @type {string}
     * @memberof ExpenseListByYearResponseDataInner
     */
    'payout_other_reason'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExpenseListByYearResponseDataInner
     */
    'payout_status'?: string;
}

